### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by PinkFloyd1213** [ogrady/DiscordCrossPosting#14]
Hello, 
I get an error when I try to launch your bot. Here is the log file. 
I hope you can help me and find the issues.

Thanks, and congrats for your work ! 

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'run'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prerun', 'run', 'postrun' ]
5 info lifecycle discordcrossposter@1.0.0~prerun: discordcrossposter@1.0.0
6 info lifecycle discordcrossposter@1.0.0~run: discordcrossposter@1.0.0
7 verbose lifecycle discordcrossposter@1.0.0~run: unsafe-perm in lifecycle true
8 verbose lifecycle discordcrossposter@1.0.0~run: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ilian Taini\Desktop\DiscordCrossPosting-master\DiscordCrossPosting-master\node_modules\.bin;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\WireGuard\;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Ilian Taini\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Ilian Taini\AppData\Local\Programs\Python\Python39\;C:\Users\Ilian Taini\AppData\Local\Microsoft\WindowsApps;C:\Users\Ilian Taini\AppData\Roaming\npm;C:\Users\Ilian Taini\.dotnet\tools
9 verbose lifecycle discordcrossposter@1.0.0~run: CWD: C:\Users\Ilian Taini\Desktop\DiscordCrossPosting-master\DiscordCrossPosting-master
10 silly lifecycle discordcrossposter@1.0.0~run: Args: [ '/d /s /c', 'node ./built/index.js' ]
11 silly lifecycle discordcrossposter@1.0.0~run: Returned: code: 1  signal: null
12 info lifecycle discordcrossposter@1.0.0~run: Failed to exec run script
13 verbose stack Error: discordcrossposter@1.0.0 run: `node ./built/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid discordcrossposter@1.0.0
15 verbose cwd C:\Users\Ilian Taini\Desktop\DiscordCrossPosting-master\DiscordCrossPosting-master
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "run"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error discordcrossposter@1.0.0 run: `node ./built/index.js`
22 error Exit status 1
23 error Failed at the discordcrossposter@1.0.0 run script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ogrady** [comment]
Hi and thanks for reporting your issue! 
I fail to reproduce this error on my machine with a fresh checkout. Did you follow more or less the following steps?

```sh
git clone ...
npm i
npm run build
cp config.json.example config.json
npm run run
```

The error `ELIFECYCLE` seems to be [related to outdated node modules](https://stackoverflow.com/a/49505612) in some cases. 
Could you please try the fix described there and report back if that fixed your issue? There is also a description on how to do this on Windows in a comment below the answer I linked.

Also: there is now a Dockerfile available in the root directory to run this bot inside a container, if that is an option for you.

**Comment by ogrady** [comment]
I'll assume the issue has resolved itself in the meantime. Feel free to open another issue if the problem occurs again.
